# general settings
name: ky-DISCNet-baseline
model_type: PSFResModel
scale: 1
num_gpu: 4
manual_seed: 10

# dataset and data loader settings
datasets:
  train:
    name: UDC-SIT-Train
    type: PairedImgPSFNpyDataset
    # Mapping config for SIT: we divide input by 1023.
    lq_map_type: norm
    gt_map_type: norm
    lq_map_range: 1023.
    gt_map_range: 1023.
    filename_tmpl: '{}'
    io_backend:
      type: npy
    folders:
      # Section that kyusu might want to change
      udc-sit-train:
        dataroot_lq: /data/s0/udc/dataset/UDC_SIT/npy/training/input
        dataroot_gt: /data/s0/udc/dataset/UDC_SIT/npy/training/GT
        meta_info_file: /home/n5/chanwoo/train-lists/Train_input_list_0412.txt
        psf_path: /home/n5/chanwoo/sit-train-psf.npy # Do not change without chanwoo's advise. Feng-provided PSF kernel code: ZTE_new_5

    gt_size: 256
    use_flip: false
    use_rot: false

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8  # per GPU
    batch_size_per_gpu: 8  # total
    dataset_enlarge_ratio: 20
    prefetch_mode: cuda
    pin_memory: true

  val:
    name: UDC-SIT-Validate
    type: PairedImgPSFNpyDataset
    lq_map_type: norm
    gt_map_type: norm
    lq_map_range: 1023.
    gt_map_range: 1023.
    io_backend:
      type: npy
    folders:
      # Section that kyusu can to change
      # Same applies with train dataset folder
      udc-sit-validate:
        dataroot_lq: /data/s0/udc/dataset/UDC_SIT/npy/validation1/input
        dataroot_gt: /data/s0/udc/dataset/UDC_SIT/npy/validation1/GT
        meta_info_file: /home/n5/chanwoo/train-lists/Validation1_input_list_0412.txt
        psf_path: /home/n5/chanwoo/sit-train-psf.npy # Do not change without chanwoo's advise. 

# network structures
# Do not change
network_g:
  type: DISCNet
  in_nc: 4
  out_nc: 4
  nf: 32
  ns: 4
  multi_scale: true
  kernel_cond: img-psf
  psf_nc: 5
  kpn_sz: 5

# path
# Do not change. If these options are modified/deleted, auto-resume might fail
path:
  pretrain_model_g: ~
  strict_load: true
  resume_state: ~

# training settings
# Do not change. These are authors' configuration.
train:
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [200000, 200000, 200000, 200000, 200000]
    restart_weights: [1, 1, 1, 1, 1]
    eta_min: !!float 1e-7

  total_iter: 1000000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: clamp_L1Loss

# validation settings
val:
  val_freq: !!float 1000000 # kyusu can change
  save_img: false # kyusu can change. set if "false" to disable image saving
  save_img_ratio: !!float 0.001 # 0 < value < 1, ratio of validation image to be saved
  dng_info: /home/chanwoo/background.dng # do not modify. This info is required to save img file.
  max_pxl: 1023.
  clamp:
    min: 0.
    max: 1.

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim: # metric name, can be arbitrary
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false
    

# logging settings
logger:
  print_freq: 250 # kyusu can change - frequency of training message
  save_checkpoint_freq: !!float 50000 # kyusu can change - frequncy of checkpointing
  # Do not modify or delete below.
  use_tb_logger: false
  wandb:
    project: ~
    resume_id: ~

# dist training settings
# Do not modify or delete below.
dist_params:
  backend: nccl
  port: 29015
